# path: .github/workflows/build.yml
name: build

on:
  pull_request:
    branches: [ develop ]
  push:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Install
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm run build

      # (tuỳ chọn) lưu artifact để debug
      - name: Upload dist
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist
