# .github/workflows/supabase.yml
name: Supabase Deploy

on:
  push:
    branches: [develop, main]
    paths:
      - "supabase/**"
  workflow_dispatch:

jobs:
  staging:
    if: github.ref == 'refs/heads/develop'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Link STAGING project
        run: supabase link --project-ref ${{ secrets.SUPABASE_STAGING_REF }}
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}

      - name: Push DB (migrations) to STAGING
        run: supabase db push
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}

      - name: Deploy all Edge Functions (STAGING)
        run: |
          for d in supabase/functions/*; do
            [ -d "$d" ] || continue
            fn=$(basename "$d")
            supabase functions deploy "$fn"
          done
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}

  production:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Link PROD project
        run: supabase link --project-ref ${{ secrets.SUPABASE_PROD_REF }}
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}

      - name: Push DB (migrations) to PROD
        run: supabase db push
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}

      - name: Deploy all Edge Functions (PROD)
        run: |
          for d in supabase/functions/*; do
            [ -d "$d" ] || continue
            fn=$(basename "$d")
            supabase functions deploy "$fn"
          done
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
